# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'thoughts.'
tagline:          'an excuse for beers'
description:      'blog'
url:              'http://misaakidis.github.io/'

author:
  name:           'Marios Isaakidis'
  nickname:       'misaakidis'
  url:            'https://twitter.com/misaakidis'
  email:          'misaakidis@yahoo.gr'

paginate:         5

## Custom vars
#version:          2.0.0

#github:            https://github.com/misaakidis
#  repo:           https://github.com/misaakidis/